Changed ProducerAvroExample to include writing with Data and MetaData schema
Can be run with the following command

mvn exec:java -Dexec.mainClass="io.confluent.examples.clients.cloud.ProducerAvroExample" -Dexec.args="$HOME/.confluent/java.config 5"

Where the first arg is the path to your config file and the second arg is the number of messages you want to produce.

Currently there is a bug where this does not work if the topic must be created due to this error

org.apache.kafka.common.errors.InvalidConfigurationException: Schema being registered is incompatible with an earlier schema for subject "SalesTransaction3-Data-value"; error code: 409; error code: 409